# Angular app service
version: '3'
services:
  app:
    image: gif-app
    container_name: gif-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'