# Angular app prod service
app:
    image: gif-app
    container_name: gif-app
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '80:80'